<div class="format_buttons"><button type="button" id="button-bold">B</button>
    <button type="button" id="button-italic">I</button>
    <button type="button" id="button-list">LI</button>
    <button type="button" id="button-link">&lt;A&gt;</button>
    <button type="button" id="button-quote">&gt;</button>
    <button type="button" id="button-header">H1</button>
    <button type="button" id="button-rule">HR</button>
</div>