version: '3.4'

services:
  mysql:
    build: ./mysql
    environment:
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_DATABASE=test_arena
    volumes:
      - ./mysql/.data:/var/lib/mysql
    command: 'mysqld --sql_mode=""'
    ports:
      - '3306:3306'
    
  arena:
    build: ../
    depends_on:
      - mysql
    environment:
      - APPLICATION_ENV=development
    volumes:
      - ../:/var/www/testArena

  nginx:
    build: ./nginx
    depends_on:
      - arena
    environment:
      - ENV=dev
      - SERVER_NAME=testarena.local
    volumes:
      - ../public:/usr/share/nginx/html:ro
    ports:
      - '80:80'